/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttackToolDetail: typeof import('./src/components/AttackToolDetail.vue')['default']
    AvoidanceDetail: typeof import('./src/components/AvoidanceDetail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    GithubPane: typeof import('./src/components/GithubPane.vue')['default']
    IconFork: typeof import('./src/components/icons/iconFork.vue')['default']
    IconGithub: typeof import('./src/components/icons/iconGithub.vue')['default']
    IconRelation: typeof import('./src/components/icons/iconRelation.vue')['default']
    IconStar: typeof import('./src/components/icons/iconStar.vue')['default']
    IconTranslate: typeof import('./src/components/icons/iconTranslate.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    RiskDetail: typeof import('./src/components/RiskDetail.vue')['default']
    RiskRelation: typeof import('./src/components/RiskRelation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
