/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttackToolDetail: typeof import('./src/components/AttackToolDetail.vue')['default']
    AvoidanceDetail: typeof import('./src/components/AvoidanceDetail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GithubPane: typeof import('./src/components/GithubPane.vue')['default']
    IconFork: typeof import('./src/components/icons/iconFork.vue')['default']
    IconGithub: typeof import('./src/components/icons/iconGithub.vue')['default']
    IconStar: typeof import('./src/components/icons/iconStar.vue')['default']
    IconTranslate: typeof import('./src/components/icons/iconTranslate.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    RiskDetail: typeof import('./src/components/RiskDetail.vue')['default']
    RiskRelation: typeof import('./src/components/RiskRelation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
